/// Nextcloud Login Flow v2 — short-lived session authentication.
///
/// Protocol reference: Nextcloud Server — "Login Flow v2" (available since NC 16).
///
/// Flow overview:
/// 1. POST `/index.php/login/v2`  → receive `LoginFlowInitResponse`
/// 2. Open `init.login` URL in the user's browser.
/// 3. Poll `init.poll.endpoint` with `token = init.poll.token` every 2 s.
/// 4. On 200 → credentials arrived; on 404 → not yet complete.
use adagio_core::error::SyncError;
use serde::{Deserialize, Serialize};
use tracing::{debug, instrument};

// ── Public types ──────────────────────────────────────────────────────────────

/// Response from POST `/index.php/login/v2`.
///
/// The `login` URL is opened in the browser and encoded in the QR code.
/// `poll` contains the endpoint and token used to retrieve credentials.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LoginFlowInitResponse {
    /// URL the user's browser must visit to authenticate.
    pub login: String,
    /// Polling configuration — endpoint and one-time token.
    pub poll: PollDetails,
}

/// Polling parameters returned by Login Flow v2 initialisation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PollDetails {
    /// One-time token sent as a form field on each poll request.
    pub token: String,
    /// URL to POST to while waiting for the user to authenticate.
    pub endpoint: String,
}

/// Credentials returned when the user has completed authentication.
///
/// `app_password` is an app-password generated by Nextcloud for this session.
/// It is stored in the OS keychain; never logged or persisted to config files.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LoginCredentials {
    /// Nextcloud server base URL (may differ from the URL used to initiate the flow).
    pub server: String,
    /// Nextcloud username of the authenticated user.
    #[serde(rename = "loginName")]
    pub login_name: String,
    /// App-password for this device session.
    #[serde(rename = "appPassword")]
    pub app_password: String,
}

// ── Public functions ──────────────────────────────────────────────────────────

/// Start a Login Flow v2 session by POSTing to `/index.php/login/v2`.
///
/// Returns the `LoginFlowInitResponse` containing the browser login URL and
/// the polling parameters. The caller is responsible for opening the browser
/// and beginning to poll.
///
/// # Errors
///
/// Returns [`SyncError::Permanent`] if the server is unreachable, returns a
/// non-200 status, or if the response body cannot be deserialised.
#[instrument(skip_all, fields(server_url))]
pub async fn begin_login_flow(server_url: &str) -> Result<LoginFlowInitResponse, SyncError> {
    let endpoint = format!("{}/index.php/login/v2", server_url.trim_end_matches('/'));

    let client = build_client()?;
    let resp = client
        .post(&endpoint)
        .send()
        .await
        .map_err(|e| SyncError::Permanent(format!("Login Flow v2 init failed: {e}")))?;

    if !resp.status().is_success() {
        return Err(SyncError::Permanent(format!(
            "Login Flow v2 init returned HTTP {}",
            resp.status()
        )));
    }

    let body = resp
        .json::<LoginFlowInitResponse>()
        .await
        .map_err(|e| SyncError::Permanent(format!("Login Flow v2 init parse failed: {e}")))?;

    debug!(login_url = %body.login, "Login Flow v2 session started");
    Ok(body)
}

/// Poll the Login Flow v2 endpoint for completed credentials.
///
/// POSTs `token=<token>` to `endpoint`.
/// - Returns `Ok(Some(credentials))` when the user has authenticated.
/// - Returns `Ok(None)` when the user has not yet authenticated (HTTP 404).
/// - Returns `Err` on any other error.
#[instrument(skip_all)]
pub async fn poll_login_flow(
    endpoint: &str,
    token: &str,
) -> Result<Option<LoginCredentials>, SyncError> {
    let client = build_client()?;
    let resp = client
        .post(endpoint)
        .form(&[("token", token)])
        .send()
        .await
        .map_err(|e| SyncError::Permanent(format!("Login Flow v2 poll failed: {e}")))?;

    match resp.status().as_u16() {
        200 => {
            let creds = resp.json::<LoginCredentials>().await.map_err(|e| {
                SyncError::Permanent(format!("Login Flow v2 poll parse failed: {e}"))
            })?;
            debug!(login_name = %creds.login_name, "Login Flow v2 credentials received");
            Ok(Some(creds))
        }
        404 => {
            debug!("Login Flow v2 poll: not yet complete");
            Ok(None)
        }
        other => Err(SyncError::Permanent(format!(
            "Login Flow v2 poll returned unexpected HTTP {other}"
        ))),
    }
}

// ── Private helpers ───────────────────────────────────────────────────────────

fn build_client() -> Result<reqwest::Client, SyncError> {
    reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(10))
        .user_agent("adagio-desktop/0.1 (Nextcloud Login Flow v2)")
        .build()
        .map_err(|e| SyncError::Permanent(format!("HTTP client build failed: {e}")))
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // T006 — Login Flow v2 protocol tests

    #[test]
    fn login_flow_init_response_deserialises_from_server_json() {
        let json = r#"{
            "poll": {
                "token": "secret-poll-token-abc123",
                "endpoint": "https://cloud.example.com/index.php/login/v2/poll"
            },
            "login": "https://cloud.example.com/index.php/login/v2/flow/abc123def456"
        }"#;
        let resp: LoginFlowInitResponse = serde_json::from_str(json).unwrap();
        assert_eq!(
            resp.login,
            "https://cloud.example.com/index.php/login/v2/flow/abc123def456"
        );
        assert_eq!(resp.poll.token, "secret-poll-token-abc123");
        assert_eq!(
            resp.poll.endpoint,
            "https://cloud.example.com/index.php/login/v2/poll"
        );
    }

    #[test]
    fn login_credentials_deserialises_camel_case_fields() {
        let json = r#"{
            "server": "https://cloud.example.com",
            "loginName": "alice",
            "appPassword": "generated-app-password-xyz"
        }"#;
        let creds: LoginCredentials = serde_json::from_str(json).unwrap();
        assert_eq!(creds.server, "https://cloud.example.com");
        assert_eq!(creds.login_name, "alice");
        assert_eq!(creds.app_password, "generated-app-password-xyz");
    }

    #[tokio::test]
    async fn poll_login_flow_returns_none_on_404() {
        let mut server = mockito::Server::new_async().await;
        let mock = server
            .mock("POST", "/poll")
            .with_status(404)
            .create_async()
            .await;

        let result = poll_login_flow(&format!("{}/poll", server.url()), "my-token")
            .await
            .unwrap();
        assert!(result.is_none(), "404 should return Ok(None)");
        mock.assert_async().await;
    }

    #[tokio::test]
    async fn poll_login_flow_returns_credentials_on_200() {
        let mut server = mockito::Server::new_async().await;
        let mock = server
            .mock("POST", "/poll")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(
                r#"{"server":"https://nc.example.com","loginName":"bob","appPassword":"pass123"}"#,
            )
            .create_async()
            .await;

        let result = poll_login_flow(&format!("{}/poll", server.url()), "my-token")
            .await
            .unwrap();
        let creds = result.expect("200 should return Some(credentials)");
        assert_eq!(creds.login_name, "bob");
        assert_eq!(creds.app_password, "pass123");
        mock.assert_async().await;
    }

    #[tokio::test]
    async fn begin_login_flow_returns_init_response_on_success() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{
            "poll": {"token": "tok", "endpoint": "http://example.com/poll"},
            "login": "http://example.com/login/flow/tok"
        }"#;
        let mock = server
            .mock("POST", "/index.php/login/v2")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;

        let resp = begin_login_flow(&server.url()).await.unwrap();
        assert_eq!(resp.poll.token, "tok");
        assert!(resp.login.contains("flow/tok"));
        mock.assert_async().await;
    }

    #[tokio::test]
    async fn begin_login_flow_errors_on_non_200() {
        let mut server = mockito::Server::new_async().await;
        let mock = server
            .mock("POST", "/index.php/login/v2")
            .with_status(503)
            .create_async()
            .await;

        let err = begin_login_flow(&server.url()).await.unwrap_err();
        assert!(
            err.to_string().contains("503"),
            "error should mention HTTP 503"
        );
        mock.assert_async().await;
    }
}
